// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package handler

import (
	"net/http"

	shortener "lucid/app/shortener/api/internal/handler/shortener"
	"lucid/app/shortener/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建新的短链接
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: shortener.CreateShortUrlHandler(serverCtx),
			},
			{
				// 获取单个短链接的详细信息和统计数据
				Method:  http.MethodGet,
				Path:    "/detail/:shortKey",
				Handler: shortener.GetShortUrlDetailHandler(serverCtx),
			},
			{
				// 获取当前用户的所有短链接
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: shortener.ListMyShortUrlsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/shortener"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 短链接重定向
				Method:  http.MethodGet,
				Path:    "/:shortKey",
				Handler: shortener.RedirectHandler(serverCtx),
			},
		},
	)
}
