// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package types

type AnalyticsRecord struct {
	IpAddress string `json:"ipAddress"` // 访客IP
	UserAgent string `json:"userAgent"` // User-Agent
	Referer   string `json:"referer"`   // 来源
	CreatedAt string `json:"createdAt"` // 访问时间
}

type CreateShortUrlReq struct {
	OriginalUrl string `json:"originalUrl" validate:"required,url"` // 原始长链接
	ExpiresIn   string `json:"expiresIn,optional"`                  //
}

type CreateShortUrlResp struct {
	ShortKey    string `json:"shortKey"`    // 生成的短链接Key
	OriginalUrl string `json:"originalUrl"` // 原始长链接
	ShortUrl    string `json:"shortUrl"`    // 完整的短链接访问地址
}

type DailySummary struct {
	Date           string `json:"date"`           // 统计日期 (YYYY-MM-DD)
	TotalClicks    int64  `json:"totalClicks"`    // 当日总点击量
	UniqueVisitors int64  `json:"uniqueVisitors"` // 当日独立访客数
}

type GetShortUrlDetailReq struct {
	ShortKey string `path:"shortKey"` // 短链接Key
}

type GetShortUrlDetailResp struct {
	Info          ShortUrlInfo      `json:"info"`          // 基本信息
	DailySummary  []DailySummary    `json:"dailySummary"`  // 每日统计
	RecentRecords []AnalyticsRecord `json:"recentRecords"` // 最近访问记录 (示例，比如最近20条)
}

type ListShortUrlsResp struct {
	Urls []ShortUrlInfo `json:"urls"` // 短链接列表
}

type RedirectReq struct {
	ShortKey string `path:"shortKey"`
}

type ShortUrlInfo struct {
	ShortKey       string `json:"shortKey"`       // 短链接Key
	OriginalUrl    string `json:"originalUrl"`    // 原始长链接
	ShortUrl       string `json:"shortUrl"`       // 完整的短链接访问地址
	CreatedAt      string `json:"createdAt"`      // 创建时间
	ExpiresAt      string `json:"expiresAt"`      // 过期时间, 为空表示永不过期
	TotalClicks    int64  `json:"totalClicks"`    // 总点击量
	UniqueVisitors int64  `json:"uniqueVisitors"` // 独立访客数
}
