// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: user.proto

package server

import (
	"context"

	"lucid/app/user/rpc/internal/logic"
	"lucid/app/user/rpc/internal/svc"
	"lucid/gen/go/user/v1"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 根据用户ID获取用户信息
func (s *UserServer) GetUserInfo(ctx context.Context, in *v1.GetUserInfoRequest) (*v1.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
