// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package types

type LoginReq struct {
	Username string `json:"username" validate:"required"` // 用户名
	Password string `json:"password" validate:"required"` // 密码
}

type LoginResp struct {
	UserID      int64  `json:"userId"`      // 用户ID
	Username    string `json:"username"`    // 用户名
	AccessToken string `json:"accessToken"` // 访问令牌
	ExpiresIn   int64  `json:"expiresIn"`   // 过期时间(秒)
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=50"` // 用户名，3-50个字符
	Password string `json:"password" validate:"required,min=6"`        // 密码，至少6个字符
}

type RegisterResp struct {
	UserID   int64  `json:"userId"`   // 用户ID
	Username string `json:"username"` // 用户名
}

type UserInfoResp struct {
	UserID    int64  `json:"userId"`    // 用户ID
	Username  string `json:"username"`  // 用户名
	CreatedAt string `json:"createdAt"` // 创建时间
}
