// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package types

type ListUsersRequest struct {
	Page     int `json:"page,optional"`     // 页码, 默认 1
	PageSize int `json:"pageSize,optional"` // 每页数量, 默认 20
}

type ListUsersResponse struct {
	Users []UserInfoResponse `json:"users"`
	Total int64              `json:"total"`
}

type LoginRequest struct {
	Username string `json:"username"` // 可以是用户名或邮箱
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"` // <--- 修改：已移除 'optional' 标签，变为必填项
}

type UserInfoResponse struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"` // 对应注册时的必填 email
	Role      string `json:"role"`  // 关键字段: 用于 Casbin 的 'sub'
	CreatedAt string `json:"created_at"`
}
